"""Phase 2: Qwen2.5-VL-7B-Instruct 4-bit Solver.

Receives an image, question, choices, and a skill generated by Phase 1.
Uses the supervisor's exact mandated prompt phrasing:
  "This is the skill to solve this question, now solve the question and give me the answer."
"""

import re
import gc
import torch
from PIL import Image
from typing import List, Dict, Any, Optional
from config import (
    QWEN_MODEL_ID,
    QUANTIZATION_CONFIG,
    SOLVER_MAX_NEW_TOKENS,
    MIN_PIXELS,
    MAX_PIXELS,
)

from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration, BitsAndBytesConfig
from qwen_vl_utils import process_vision_info


class QwenSolver:
    """Phase 2 Local VLM Solver with 4-bit Quantization."""

    def __init__(self, model_id: str = QWEN_MODEL_ID):
        self.model_id = model_id
        self.model = None
        self.processor = None
        self._is_loaded = False

    def load_model(self):
        """Lazy load model and processor in 4-bit precision."""
        if self._is_loaded:
            return

        print(f"[Qwen Solver] Loading {self.model_id} in 4-bit NF4 precision...")
        print(f"[Qwen Solver] Image resolution bounds: min_pixels={MIN_PIXELS}, max_pixels={MAX_PIXELS}")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=QUANTIZATION_CONFIG["load_in_4bit"],
            bnb_4bit_compute_dtype=getattr(torch, QUANTIZATION_CONFIG["bnb_4bit_compute_dtype"]),
            bnb_4bit_quant_type=QUANTIZATION_CONFIG["bnb_4bit_quant_type"],
            bnb_4bit_use_double_quant=QUANTIZATION_CONFIG["bnb_4bit_use_double_quant"],
        )
        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_id,
            quantization_config=bnb_config,
            device_map="auto",
            torch_dtype=torch.float16,
        )
        self.processor = AutoProcessor.from_pretrained(
            self.model_id,
            min_pixels=MIN_PIXELS,
            max_pixels=MAX_PIXELS,
        )
        self._is_loaded = True
        print("[Qwen Solver] Model loaded successfully.")

    def solve(
        self,
        image: Image.Image,
        question: str,
        choices: List[str],
        mode: str = "baseline",
        skill: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Solve a visual question. Modes: 'baseline' or 'adaptive_skills'."""
        self.load_model()

        # Format choices
        labels = ["A", "B", "C", "D", "E", "F"]
        options_text = "\n".join(
            f"({labels[i]}) {c}" for i, c in enumerate(choices)
        )

        # Build prompt based on mode
        if mode in ["ace", "adaptive_skills"] and skill:
            prompt_text = (
                f"Context Playbook:\n"
                f"{skill}\n\n"
                f"Question: {question}\n\n"
                f"Choices:\n{options_text}\n\n"
                f"Solve the question using the strategies above. State your final answer choice clearly as (A), (B), (C), (D), or (E)."
            )
        else:  # baseline — direct VQA
            prompt_text = (
                f"Question: {question}\n\n"
                f"Choices:\n{options_text}\n\n"
                f"Select the correct answer option directly as (A), (B), (C), (D), or (E)."
            )

        raw_text, prediction = self._generate(image, prompt_text, choices=choices)
        self.clear_memory()

        return {
            "prediction": prediction,
            "raw_output": raw_text,
            "prompt_used": prompt_text,
            "mode": mode,
        }

    def _generate(self, image: Image.Image, prompt_text: str, choices: Optional[List[str]] = None):
        """Execute Qwen2.5-VL forward pass."""
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": prompt_text},
                ],
            }
        ]

        text = self.processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)

        inputs = self.processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        ).to(self.model.device)

        with torch.no_grad():
            generated_ids = self.model.generate(
                **inputs,
                max_new_tokens=SOLVER_MAX_NEW_TOKENS,
                do_sample=False,
            )

        trimmed = [
            out_ids[len(in_ids):]
            for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = self.processor.batch_decode(
            trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        prediction = self._parse_option_letter(output_text, choices=choices)
        return output_text, prediction

    def generate_text(
        self,
        system_prompt: str,
        user_prompt: str,
        image: Optional[Image.Image] = None,
        max_new_tokens: int = 256,
    ) -> str:
        """Generate text/JSON using Qwen2.5-VL for skill generation and reflection."""
        self.load_model()

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})

        user_content = []
        if image is not None:
            user_content.append({"type": "image", "image": image})
        user_content.append({"type": "text", "text": user_prompt})
        messages.append({"role": "user", "content": user_content})

        text = self.processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        if image is not None:
            image_inputs, video_inputs = process_vision_info(messages)
        else:
            image_inputs, video_inputs = None, None

        inputs = self.processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        ).to(self.model.device)

        with torch.no_grad():
            generated_ids = self.model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=False,
            )

        trimmed = [
            out_ids[len(in_ids):]
            for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = self.processor.batch_decode(
            trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        self.clear_memory()
        return output_text

    @staticmethod
    def _parse_option_letter(text: str, choices: Optional[List[str]] = None) -> str:
        """Extract choice option letter (A)-(E) from model output."""
        # 1. Explicit bracketed format: (A), (B), etc.
        match = re.search(r"\(([A-E])\)", text, re.IGNORECASE)
        if match:
            return f"({match.group(1).upper()})"
        # 2. "Answer: A" or "Choice A" or "Option A"
        match = re.search(r"\b(?:Answer|Choice|Option|is|select)\s*:?\s*\(?([A-E])\)?\b", text, re.IGNORECASE)
        if match:
            return f"({match.group(1).upper()})"
        # 3. Standalone letter on its own word
        match = re.search(r"\b([A-E])\b", text)
        if match:
            return f"({match.group(1).upper()})"
        
        # 4. Fallback: match against choice values if provided
        if choices:
            labels = ["A", "B", "C", "D", "E", "F"]
            for idx, c in enumerate(choices):
                if idx < len(labels) and c.strip():
                    pattern = r"\b" + re.escape(c.strip()) + r"\b"
                    if re.search(pattern, text, re.IGNORECASE):
                        return f"({labels[idx]})"

        return "(UNKNOWN)"

    @staticmethod
    def clear_memory():
        """Explicitly clear CUDA cache to prevent OOM on T4."""
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
