"""Phase 2: Qwen2.5-VL-7B-Instruct 4-bit Solver.

Receives an image, question, choices, and a skill generated by Phase 1.
Uses the supervisor's exact mandated prompt phrasing:
  "This is the skill to solve this question, now solve the question and give me the answer."
"""

import re
import gc
import torch
from PIL import Image
from typing import List, Dict, Any, Optional
from config import QWEN_MODEL_ID, QUANTIZATION_CONFIG, SOLVER_MAX_NEW_TOKENS

try:
    from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration, BitsAndBytesConfig
    from qwen_vl_utils import process_vision_info
    HAS_TRANSFORMERS = True
except ImportError:
    HAS_TRANSFORMERS = False


class QwenSolver:
    """Phase 2 Local VLM Solver with 4-bit Quantization."""

    def __init__(self, model_id: str = QWEN_MODEL_ID):
        self.model_id = model_id
        self.model = None
        self.processor = None
        self._is_loaded = False

    def load_model(self):
        """Lazy load model and processor in 4-bit precision."""
        if self._is_loaded:
            return

        if not HAS_TRANSFORMERS:
            print("[Qwen Solver] Transformers not installed. Running in mock mode.")
            self._is_loaded = True
            return

        print(f"[Qwen Solver] Loading {self.model_id} in 4-bit NF4 precision...")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=QUANTIZATION_CONFIG["load_in_4bit"],
            bnb_4bit_compute_dtype=getattr(torch, QUANTIZATION_CONFIG["bnb_4bit_compute_dtype"]),
            bnb_4bit_quant_type=QUANTIZATION_CONFIG["bnb_4bit_quant_type"],
            bnb_4bit_use_double_quant=QUANTIZATION_CONFIG["bnb_4bit_use_double_quant"],
        )
        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_id,
            quantization_config=bnb_config,
            device_map="auto",
            torch_dtype=torch.float16,
        )
        self.processor = AutoProcessor.from_pretrained(self.model_id)
        self._is_loaded = True
        print("[Qwen Solver] Model loaded successfully.")

    def solve(
        self,
        image: Image.Image,
        question: str,
        choices: List[str],
        mode: str = "baseline",
        skill: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Solve a visual question. Modes: 'baseline' or 'adaptive_skills'."""
        self.load_model()

        # Format choices
        labels = ["A", "B", "C", "D", "E", "F"]
        options_text = "\n".join(
            f"({labels[i]}) {c}" for i, c in enumerate(choices)
        )

        # Build prompt based on mode
        if mode == "adaptive_skills" and skill:
            # Supervisor's EXACT mandated phrasing
            prompt_text = (
                f"This is the skill to solve this question, "
                f"now solve the question and give me the answer.\n\n"
                f"Skill:\n{skill}\n\n"
                f"Question: {question}\n"
                f"Choices:\n{options_text}"
            )
        else:  # baseline — direct VQA
            prompt_text = (
                f"Question: {question}\n\n"
                f"Choices:\n{options_text}\n\n"
                f"Select the correct answer."
            )

        if not HAS_TRANSFORMERS or self.model is None:
            raw_text = "Mock prediction: (A)"
            prediction = "(A)"
        else:
            raw_text, prediction = self._generate(image, prompt_text)

        self.clear_memory()

        return {
            "prediction": prediction,
            "raw_output": raw_text,
            "prompt_used": prompt_text,
            "mode": mode,
        }

    def _generate(self, image: Image.Image, prompt_text: str):
        """Execute Qwen2.5-VL forward pass."""
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": prompt_text},
                ],
            }
        ]

        text = self.processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)

        inputs = self.processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        ).to(self.model.device)

        with torch.no_grad():
            generated_ids = self.model.generate(
                **inputs,
                max_new_tokens=SOLVER_MAX_NEW_TOKENS,
                do_sample=False,
            )

        trimmed = [
            out_ids[len(in_ids):]
            for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = self.processor.batch_decode(
            trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        prediction = self._parse_option_letter(output_text)
        return output_text, prediction

    @staticmethod
    def _parse_option_letter(text: str) -> str:
        """Extract choice option letter (A)-(E) from model output."""
        # Explicit bracketed format: (A), (B), etc.
        match = re.search(r"\(([A-E])\)", text, re.IGNORECASE)
        if match:
            return f"({match.group(1).upper()})"
        # "Answer: A" format
        match = re.search(r"\bAnswer:\s*([A-E])\b", text, re.IGNORECASE)
        if match:
            return f"({match.group(1).upper()})"
        # Standalone letter
        match = re.search(r"\b([A-E])\b", text)
        if match:
            return f"({match.group(1).upper()})"
        return "(UNKNOWN)"

    @staticmethod
    def clear_memory():
        """Explicitly clear CUDA cache to prevent OOM on T4."""
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
